sudo: true
language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - rm -rf ~/.gnupg
  - sudo apt-get install xvfb

before_script:
  ## PHP_CodeSniffer
  - pear uninstall php_codesniffer
  - pear config-set bin_dir /usr/local/bin
  - sudo pear install php_codesniffer
  - git clone git://github.com/wimg/PHPCompatibility.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/PHPCompatibility
  - phpenv rehash
  - phpcs -i
  - phpcs --config-set error_severity 1
  - phpcs --config-set warning_severity 0

script:
  ## PHP_CodeSniffer
  - phpcs --standard=PHPCompatibility --runtime-set testVersion 5.3-5.5 $(find ./ -name '*.php')

notifications:
  slack:
    secure: E9tbxOZ/n4Gcwi8SiCKQ5QVw+5AfwdTq4e/VG4epQF74IqXmJJvaJgQSVKLSVXJm4O1u8JHd+ffN1Xheh1FDaKkscuJYQcT4D+oOc40bHhb0tS71v1fAMzMX7NuyqgEu2a8dbYo7bqVKtdj/EBbOPWnwgfMuA6ylTItVf294spA=
