sudo: required
language: php
php:
- 5.3
- 5.4
env:
- WP_VERSION=4.0 WP_MULTISITE=0
before_install:
- rm -rf ~/.gnupg
- sudo apt-get install xvfb
before_script:
- pyrus install pear/PHP_CodeSniffer
- git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
- git clone git://github.com/wimg/PHPCompatibility.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/PHPCompatibility
- phpenv rehash
- ls $(pear config-get php_dir)
- ls $(pear config-get php_dir)/PHP
- ls $(pear config-get php_dir)/PHP/CodeSniffer
- ls $(pear config-get php_dir)/PHP/CodeSniffer/Standards
- ls /usr/share/pear/PHP/CodeSniffer/Standards/PHPCompatibility/
- export PLUGIN_DIR=$(pwd)
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz*
- sudo apt-get -qq autoremove
- sudo apt-get update
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- sudo wget -qO ee rt.cx/ee && sudo bash ee
- source /etc/bash_completion.d/ee_auto.rc
- sudo ee -v
- sudo lsb_release  -a
- sudo ee site create wp.localtest.me --wp --user=ADMINUSER --email=ritesh.patel@rtcamp.com
  --pass=ADMINPASS
- sudo chmod 777 -R /var/www
- sudo cat /etc/mysql/conf.d/my.cnf
- sudo nginx -t
- sudo service nginx reload
- cd /var/www/wp.localtest.me/htdocs/wp-content/plugins/ && ls
- mkdir rtmedia
- cd $PLUGIN_DIR
- cp -Rf * /var/www/wp.localtest.me/htdocs/wp-content/plugins/rtmedia/
- cd /var/www/wp.localtest.me/htdocs/
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.2.3.1.zip
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/bbpress.2.5.7.zip
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/rtsocial.2.1.18.zip
- wp plugin activate --all
- wp --allow-root user create EDITORUSER editor@localtest.me --role=editor --user_pass=EDITORPASS
- wp --allow-root user create AUTHORUSER author@localtest.me --role=author --user_pass=AUTHORPASS
- wp --allow-root user create CONTRIBUTORUSER contributor@localtest.me --role=contributor
  --user_pass=CONTRIBUTORPASS
- wp --allow-root user create SUBSCRIBERUSER subscriber@localtest.me --role=author
  --user_pass=SUBSCRIBERPASS
- cd $PLUGIN_DIR
- cd tests/functional/
- npm install -g nightwatch
- npm install
- git clone --depth=1 https://github.com/rtCamp/rtmedia-test-data.git test-data
script:
- phpcs --standard=$(if [ -e ruleset.xml ]; then echo ruleset.xml; else echo WordPress;
  fi) $(find /var/www/wp.localtest.me/htdocs/wp-content/plugins/rtmedia/ -name '*.php')
- phpcs --standard=PHPCompatibility --runtime-set testVersion 5.3-5.6 $(find /var/www/wp.localtest.me/htdocs/wp-content/plugins/rtmedia/
  -name '*.php')
notifications:
  slack:
    secure: E9tbxOZ/n4Gcwi8SiCKQ5QVw+5AfwdTq4e/VG4epQF74IqXmJJvaJgQSVKLSVXJm4O1u8JHd+ffN1Xheh1FDaKkscuJYQcT4D+oOc40bHhb0tS71v1fAMzMX7NuyqgEu2a8dbYo7bqVKtdj/EBbOPWnwgfMuA6ylTItVf294spA=
